server:
  port: 9005

spring:
  application:
    name: sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos server地址

    sentinel:
      transport:
        dashboard: 127.0.0.1:9001  # sentinel控制台地址
      eager: true                  # 取消懒加载，不然需要请求接口后，dashboard才看得到服务
