spring:
  application:
    name: swagger-demo
  profiles:
    active: dev



server:
  port: 9001



knife4j:

  enable: false # true 是开启增强配置

#  production: true # 开启生产环境屏蔽

  basic:
    enable: true
    username: test # Basic认证用户名
    password: 123  # Basic认证密码

