// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

package com.hollly.example.grpc;

public final class GreeterTestProto {
  private GreeterTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test1_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test1_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test1_TestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test1_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGreeter.proto\022\005test1\"(\n\013TestRequest\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"-\n\014TestResponse" +
      "\022\017\n\007message\030\001 \001(\t\022\014\n\004code\030\002 \001(\t2E\n\007Greet" +
      "er\022:\n\rTestSomeThing\022\022.test1.TestRequest\032" +
      "\023.test1.TestResponse\"\000B2\n\027com.hollly.exa" +
      "mple.grpcB\020GreeterTestProtoP\001\242\002\002WYb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test1_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test1_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test1_TestRequest_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_test1_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test1_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test1_TestResponse_descriptor,
        new java.lang.String[] { "Message", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
