// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

package com.hollly.example.grpc;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test1.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
